/**
 * Tests for Gradle configuration cache settings in gradle.properties
 *
 * PROBLEM: Expo SDK 54's generated app/build.gradle uses .execute() which is
 * NOT compatible with Gradle 8+ configuration cache. This causes build failures
 * when --configuration-cache is enabled.
 *
 * SOLUTION: Disable configuration cache for Expo SDK 54 compatibility:
 * 1. Workflow disables org.gradle.configuration-cache in gradle.properties
 * 2. NO --configuration-cache flag in gradlew commands
 * 3. org.gradle.caching=true remains enabled for build cache benefits
 *
 * FUTURE: Once Expo SDK fixes the template to use providers.exec instead of
 * .execute(), we can re-enable configuration cache.
 *
 * Related: build-android.yml includes "Disable Gradle configuration cache" step
 */

import * as fs from 'fs';
import * as path from 'path';

const MONOREPO_ROOT = path.resolve(__dirname, '../../../..');
const APP_ROOT = path.resolve(__dirname, '../..');
const GRADLE_PROPERTIES_PATH = path.join(APP_ROOT, 'android', 'gradle.properties');

describe('Gradle Configuration Cache Settings', () => {
    const androidDirExists = fs.existsSync(path.join(APP_ROOT, 'android'));
    let gradleProperties: string;

    beforeAll(() => {
        if (androidDirExists) {
            gradleProperties = fs.readFileSync(GRADLE_PROPERTIES_PATH, 'utf-8');
        }
    });

    describe('Unit: Configuration cache property (Expo SDK 54 - DISABLED)', () => {
        it('should have org.gradle.configuration-cache=true in Expo-generated file', () => {
            if (!androidDirExists) {
                console.log('⚠️  Skipping: android/ directory not generated yet (run expo prebuild)');
                return;
            }
            // Expo SDK 54 prebuild generates gradle.properties with config-cache=true
            // BUT the workflow disables it post-prebuild due to .execute() incompatibility
            // This test validates the Expo-generated default is present
            expect(gradleProperties).toContain('org.gradle.configuration-cache=true');
        });

        it('should have org.gradle.configuration-cache.problems=warn in Expo-generated file', () => {
            if (!androidDirExists) {
                console.log('⚠️  Skipping: android/ directory not generated yet (run expo prebuild)');
                return;
            }
            // Expo generates this setting, but since we disable config-cache entirely,
            // this setting becomes moot. Still validated for consistency.
            expect(gradleProperties).toContain('org.gradle.configuration-cache.problems=warn');
        });

        it('should have org.gradle.caching=true', () => {
            if (!androidDirExists) {
                console.log('⚠️  Skipping: android/ directory not generated yet (run expo prebuild)');
                return;
            }
            // Gradle build cache stores task outputs and reuses them when inputs haven't changed.
            // This complements configuration cache:
            // - Configuration cache: skips build script evaluation
            // - Build cache: skips task execution when inputs match
            //
            // Together they provide maximum build speed improvement.
            expect(gradleProperties).toContain('org.gradle.caching=true');
        });
    });

    describe('Unit: Property value correctness (Expo SDK 54 - config-cache DISABLED)', () => {
        it('Expo-generated gradle.properties has config-cache enabled by default', () => {
            if (!androidDirExists) {
                console.log('⚠️  Skipping: android/ directory not generated yet (run expo prebuild)');
                return;
            }
            // The gradle.properties file is generated by Expo with config-cache=true
            // The workflow then APPENDS org.gradle.configuration-cache=false to override it
            // This test validates the Expo-generated default is true
            const lines = gradleProperties.split('\n');
            const configCacheLines = lines.filter(
                (line) => line.startsWith('org.gradle.configuration-cache=') && !line.startsWith('#')
            );

            // Should have at least the Expo-generated line
            expect(configCacheLines.length).toBeGreaterThanOrEqual(1);

            // First occurrence (Expo-generated) should be true
            expect(configCacheLines[0]).toBe('org.gradle.configuration-cache=true');
        });

        it('should not have configuration-cache.problems set to fail', () => {
            if (!androidDirExists) {
                console.log('⚠️  Skipping: android/ directory not generated yet (run expo prebuild)');
                return;
            }
            // Setting problems=fail would cause builds to break on any
            // configuration cache incompatibility, which is too strict
            // for a React Native project with many third-party plugins.
            const lines = gradleProperties.split('\n');
            const problemsLine = lines.find(
                (line) => line.startsWith('org.gradle.configuration-cache.problems=') && !line.startsWith('#')
            );

            expect(problemsLine).toBeDefined();
            expect(problemsLine).not.toBe('org.gradle.configuration-cache.problems=fail');
        });

        it('should not have caching set to false', () => {
            if (!androidDirExists) {
                console.log('⚠️  Skipping: android/ directory not generated yet (run expo prebuild)');
                return;
            }
            const lines = gradleProperties.split('\n');
            const cachingLine = lines.find(
                (line) => line.startsWith('org.gradle.caching=') && !line.startsWith('#')
            );

            expect(cachingLine).toBeDefined();
            expect(cachingLine).not.toBe('org.gradle.caching=false');
        });
    });

    describe('Integration: Gradle properties coexistence', () => {
        it('should have parallel builds enabled (independent from config-cache)', () => {
            if (!androidDirExists) {
                console.log('⚠️  Skipping: android/ directory not generated yet (run expo prebuild)');
                return;
            }
            // Parallel builds remain enabled for performance
            // Config-cache is disabled due to Expo SDK 54 incompatibility, but that's separate
            expect(gradleProperties).toContain('org.gradle.parallel=true');
        });

        it('should coexist with existing JVM args', () => {
            if (!androidDirExists) {
                console.log('⚠️  Skipping: android/ directory not generated yet (run expo prebuild)');
                return;
            }
            // JVM args and cache settings are independent
            expect(gradleProperties).toMatch(/org\.gradle\.jvmargs=/);
        });

        it('may have config-cache setting twice (Expo-generated true + workflow-appended false)', () => {
            if (!androidDirExists) {
                console.log('⚠️  Skipping: android/ directory not generated yet (run expo prebuild)');
                return;
            }
            // Expo generates gradle.properties with config-cache=true
            // Workflow appends config-cache=false to override it
            // This is intentional - Gradle uses the LAST occurrence
            const configCacheMatches = gradleProperties.match(/^org\.gradle\.configuration-cache=.+$/gm);
            const problemsMatches = gradleProperties.match(/^org\.gradle\.configuration-cache\.problems=.+$/gm);
            const cachingMatches = gradleProperties.match(/^org\.gradle\.caching=.+$/gm);

            // Config-cache may appear 1 (Expo only) or 2 times (Expo + workflow override)
            expect(configCacheMatches.length).toBeGreaterThanOrEqual(1);
            expect(configCacheMatches.length).toBeLessThanOrEqual(2);

            // Problems and caching should appear exactly once
            expect(problemsMatches).toHaveLength(1);
            expect(cachingMatches).toHaveLength(1);
        });
    });

    describe('E2E: Workflow DISABLES configuration cache (Expo SDK 54 compatibility)', () => {
        let workflowContent: string;

        beforeAll(() => {
            workflowContent = fs.readFileSync(
                path.join(MONOREPO_ROOT, '.github', 'workflows', 'build-android.yml'),
                'utf-8'
            );
        });

        it('should NOT pass --configuration-cache flag to gradlew command', () => {
            // Expo SDK 54 app/build.gradle uses .execute() which is NOT config-cache safe
            // Therefore we must NOT use --configuration-cache flag
            expect(workflowContent).not.toContain('--configuration-cache');
        });

        it('should have step to disable configuration cache in gradle.properties', () => {
            // After expo prebuild (which generates gradle.properties with config-cache=true),
            // we need to append org.gradle.configuration-cache=false to disable it
            expect(workflowContent).toContain('Disable Gradle configuration cache');
            expect(workflowContent).toContain('org.gradle.configuration-cache=false');
            expect(workflowContent).toContain('packages/app/android/gradle.properties');
        });

        it('should use setup-gradle action which supports configuration cache', () => {
            // gradle/actions/setup-gradle@v4 automatically manages
            // the configuration cache directory alongside other caches.
            expect(workflowContent).toContain('gradle/actions/setup-gradle');
        });

        it('should have cache-read-only for non-master branches', () => {
            // Non-master branches should not pollute the configuration cache.
            // This prevents cache thrashing from feature branch variations.
            expect(workflowContent).toMatch(/cache-read-only/);
        });
    });
});
